apiVersion: apps/v1
kind: Deployment
metadata:
  name: bci2token
  labels:
    app: bci2token
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bci2token
  template:
    metadata:
      labels:
        app: bci2token
    spec:
      containers:
      - name: bci2token
        image: bci2token:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "WARNING"
        resources:
          limits:
            memory: "2048Mi"
            cpu: "4"
          requests:
            memory: "1024Mi"
            cpu: "2.0"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bci2token-service
spec:
  selector:
    app: bci2token
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
